### ISSUE TITLE
After upgrade to through@2.3.10, build failure with error Cannot find moudle 'call-bind'

### ISSUE THREAD

**Issue by charlesh21** [ljharb/through#1]
Hi ljhard,

When my project upgrade to 2.3.10, the build failure with the error Cannot find moudle 'call-bind'

Do you know hot to fix this error?

Thanks,
Charles

**Comment by Daviot** [comment]
@charlesh21 The issue is that a new dependency "call-bind" has been introduced in version 2.3.10 with the commit https://github.com/ljharb/through/commit/3fc8de1dd6b5c69ebca1b212d4852ca11e853cb2, but it is missing in the package.json.

I had the same issue and resolved it by installing call-bin in my project directly.
Just add `"call-bind": "^1"` to your package.json or install it with npm install call-bind

Hope it helps

**Comment by charlesh21** [comment]
Hi @Daviot 

Yes, I already added the call-bind into my project package.json as a temp fix.

Thanks

**Comment by LudovicSterlin** [comment]
Yes same issue here.
Just submitted an MR #2

**Comment by Marak** [comment]
:-)

Good morning.

This somehow sync'd up with us today. Friendly reminded to lock package versions if you depend on them.

**Comment by jan-molak** [comment]
Hi @ljharb, it looks like the latest version of `through` has a missing dependency on `call-bind`. 

This prevents [`inquirer`](https://www.npmjs.com/package/inquirer) from running (see https://github.com/SBoudrias/Inquirer.js/issues/1317) and affects all the projects that rely on it, including WebdriverIO https://github.com/webdriverio/webdriverio/issues/11399:

```
[wdio] Error: Cannot find module 'call-bind'
[wdio] Require stack:
[wdio] - /Users/example/tmp/node_modules/@ljharb/through/index.js
[wdio]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[wdio]     at Module._load (node:internal/modules/cjs/loader:922:27)
[wdio]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[wdio]     at require (node:internal/modules/cjs/helpers:119:18)
[wdio]     at Object.<anonymous> (/Users/example/tmp/node_modules/@ljharb/through/index.js:4:16)
[wdio]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[wdio]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[wdio]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[wdio]     at Module._load (node:internal/modules/cjs/loader:960:12)
[wdio]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
[wdio]     at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
[wdio]   code: 'MODULE_NOT_FOUND',
```

I believe that PR https://github.com/ljharb/through/pull/2 and a new release of `through` should resolve this issue.

Thanks!

**Comment by ljharb** [comment]
Whoops, thanks. I’ll have a fix published shortly.
